# Generated by Django 5.0.6 on 2024-07-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=12)),
                ('task_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
