# Generated by Django 5.0.6 on 2024-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=12)),
                ('task_desc', models.CharField(max_length=100)),
                ('task_completion', models.BooleanField(default=False)),
                ('task_assign', models.DateField()),
            ],
        ),
    ]
